version: '3'

services:
  keycloak:
    image: mstanuch/keycloak-custom-spi:latest
    container_name: keycloak_custom_spi
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080